version: '3.0'
services:
  budgetplanner:
    image: tivix-budget-planner-api:local
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: very_s3cure_p@ssw0rd!
    volumes:
      - './drive:/var/opt/mssql'
    ports:
      - '1433:1433'
    restart: always