version: '3.0'
services:
  budgetplanner:
    image: tivix-budget-planner-api:local
    build:
      context: .
    ports:
      - '8080:80'
    depends_on:
      - postgres
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: 'very_s3cure_p@ssw0rd!'
      POSTGRES_USER: 'coolkid'
    ports:
      - '5432:5432'
    restart: always